<a href="https://colab.research.google.com/github/Srikruthi1418/AIML-BATCH-20/blob/main/part1_assign1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
list1=[4,5,6,7]
array1=np.array(list1)
print ("list",list1)
print("array",array1)

list [4, 5, 6, 7]
array [4 5 6 7]


In [2]:
print("type of list1:",type(list1))
print("type of array1:",type(array1))

type of list1: <class 'list'>
type of array1: <class 'numpy.ndarray'>


In [4]:
a1=[5,6,7,8]
a2=[1,5,6,9]
a=np.add(a1,a2)
print(a)
s=np.subtract(a1,a2)
print(s)
m=np.multiply(a1,a2)
print(m)
d=np.divide(a1,a2)
print(d)
p=np.power(a1,a2)
print(p)

[ 6 11 13 17]
[ 4  1  1 -1]
[ 5 30 42 72]
[5.         1.2        1.16666667 0.88888889]
[        5      7776    117649 134217728]


In [5]:
n1=input()
n2=input()
n=np.char.add(n1,n2)
print(n)

abc
def
abcdef


In [6]:
# sin
x = np.pi / 4
sin_result = np.sin(x)
print("sin(x):",sin_result)

#log
x = 10
log_result = np.log(x)
print("log(x):",log_result)

#log2
x = 16
log2_result = np.log2(x)
print("log2(x):",log2_result)

#exp
x = 2
exp_result = np.exp(x)
print("exp(x):",exp_result)



sin(x): 0.7071067811865475
log(x): 2.302585092994046
log2(x): 4.0
exp(x): 7.38905609893065
